trigger:
- '*'

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  wwwrootDir: 'Tailspin.SpaceGame.Web/wwwroot'
  dotnetSdkVersion: '8.x'

steps:

- task: UseDotNet@2
  displayName: 'Install .NET SDK 8.x'
  inputs:
    packageType: 'sdk'
    version: '$(dotnetSdkVersion)'
    installationPath: $(Agent.ToolsDirectory)/dotnet

- task: NodeTool@0
  displayName: 'Install Node.js'
  inputs:
    versionSpec: '18.x'  # Poți ajusta versiunea după cerințele proiectului
    checkLatest: true

- task: Npm@1
  displayName: 'Install npm dependencies'
  inputs:
    command: 'install'

- script: './node_modules/.bin/node-sass $(wwwrootDir) --output $(wwwrootDir)'
  displayName: 'Compile Sass assets'

- task: Gulp@1
  displayName: 'Run Gulp tasks'
  inputs:
    gulpFile: 'gulpfile.js'
    targets: 'default'
    workingDirectory: '$(Build.SourcesDirectory)'

- script: |
    echo "$(Build.DefinitionName), $(Build.BuildId), $(Build.BuildNumber)" > buildinfo.txt
  displayName: 'Write build info'
  workingDirectory: '$(wwwrootDir)'

- task: DotNetCoreCLI@2
  displayName: 'Restore .NET project dependencies'
  inputs:
    command: 'restore'
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: 'Build the project'
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--no-restore --configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Publish the project - $(buildConfiguration)'
  inputs:
    command: 'publish'
    projects: '**/*.csproj'
    publishWebProjects: false
    arguments: '--no-build --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/$(buildConfiguration)'
    zipAfterPublish: true
  
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  condition: succeeded()
